modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
logoFile="assets/solarneutronactivatortweak/Solar_Neutron_Activator.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/solar-neutron-activator-tweak"
credits="Created by Kentanto"
authors="Kentanto"

[[mods]]
modId="solarneutronactivatortweak"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[mixins]]
config="solarneutronactivatortweak.mixins.json"

[[dependencies.solarneutronactivatortweak]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.solarneutronactivatortweak]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
