org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Shared mod info
mod_id=solarneutronactivatortweak
mod_name=Solar Neutron Activator Tweak
mod_license=MIT
mod_version=1.1.0
mod_group_id=com.kentanto.alwayssna
mod_authors=Kentanto
mod_description=Allows Mekanism Solar Neutron Activator to run without sunlight, in any dimension, day or night.

# ===== NeoForge 1.21.1 =====
parchment_minecraft_version_1_21_1=1.21
parchment_mappings_version_1_21_1=2024.07.28
minecraft_version_1_21_1=1.21.1
neo_version_1_21_1=21.1.65

# ===== NeoForge 1.20.1 =====
minecraft_version_1_20_1=1.20.1
neo_version_1_20_1=47.1.106

# ===== Forge 1.20.1 =====
forge_version_1_20_1=47.3.0

