modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
logoFile="assets/solarneutronactivatortweak/Solar_Neutron_Activator.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/solar-neutron-activator-tweak"
credits="Created by Kentanto"
authors="Kentanto"

[[mods]]
modId="solarneutronactivatortweak"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[mixins]]
config="solarneutronactivatortweak.mixins.json"

[[dependencies.solarneutronactivatortweak]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.solarneutronactivatortweak]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
